name: Build Executables

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Build executable on Windows
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --add-data "icons/icon.ico;icons" --add-data "icons/icon.png;icons" image-flipper.py

    - name: Build executable on macOS
      if: matrix.os == 'macos-latest'
      run: |
        pip install py2app && python setup.py py2app


    - name: Build executable on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --add-data "icons/icon.ico:icons" --add-data "icons/icon.png:icons" image-flipper.py

    - name: Upload artifact on Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: executable-windows
        path: dist/image-flipper.exe

    - name: Upload artifact on macOS
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: executable-macos
        path: "dist/Image Flipper.app"

    - name: Upload artifact on Linux
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: executable-linux
        path: dist/image-flipper